[package]
name = "mscfb-cf"
version = "0.1.0"
edition = "2024"

[lib]
name = "mscfb_cf"
path = "sources/library.rs"

[dependencies]
mscfb-pod = { path = "../mscfb-pod" }
mscfb-utils = { path = "../mscfb-utils" }

# TODO: Pourrait être fait main.
memmap2 = { version = "0.9.11", default-features = false }

[features]
default = [ "pedantic", "sync" ]
pedantic = []
sync = []
